modLoader="javafml"
loaderVersion="[2,)" # Compatible with any FML version 2.x
license="Custom: Personal Non-Commercial License"

[[mods]]
modId="foxai"
version="${file.jarVersion}" # Automatically uses the version from build.gradle
displayName="FoxAi"
displayURL="https://modrinth.com/mod/foxai"
credits="Made by ItsmcFox"
authors="ItsmcFox"
description='''
FoxAi is an AI-powered Minecraft companion mod built using NeoForge.
It features learning behaviors, pathfinding, and player interaction.
'''

# Optional: Required dependencies
[[dependencies.foxai]]
modId="neoforge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"
