modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "foxai"
version = "1.0.0"
displayName = "FoxAi"
authors = "itsmcfox"
description = "Advanced AI that learns from players and acts like a real one"
