name: Build Mod

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Can be replaced with windows-latest or macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adoptopenjdk'

      - name: Set up Gradle Wrapper
        run: ./gradlew wrapper

      - name: Build the Mod
        run: ./gradlew build
        
      - name: Upload JAR to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mod-artifact
          path: build/libs/*.jar
